/**
 * Guided-tour definitions. SPIKE — not production content.
 *
 * A tour is plain data: an ordered list of steps, each pointing at a
 * `[data-tour="…"]` anchor (or no anchor, for a centred intro/outro card).
 * Keeping tours as data — not code — is the point: the same shape can later be
 * hand-written, generated by an AI from the app's knowledge base, or served by
 * an API, and the player in `run-tour.ts` stays unchanged.
 *
 * Steps whose anchor is not on screen are skipped (or, with `keep`, shown as a
 * centred card), so one tour can span page states — e.g. the profile role
 * picker and the form that follows it.
 */
export interface GuideStep {
  /**
   * Element to highlight. A list is tried in order and the first one on screen
   * wins. Omit for a centred card.
   */
  element?: string | string[];
  /**
   * Show the step as a centred card when none of its elements are on screen,
   * instead of skipping it. For steps whose text matters on its own.
   */
  keep?: boolean;
  title: string;
  description: string;
}

export interface GuideTour {
  id: string;
  /** Shown in the "How do I…" menu. */
  title: string;
  /**
   * Where the tour starts. The menu goes here first when `matches` is false;
   * on the same page only its query is merged in, so the chosen network stays.
   * (Views such as map/list are switched with `prepare`, not the URL: the home
   * page reads `?view=` only on load.)
   */
  path: string;
  /** Whether this tour belongs to the current page (and view). */
  matches: (pathname: string, params: URLSearchParams) => boolean;
  /**
   * An element that proves the page (or view) the tour is about is on screen.
   * Needed when starting the tour switches views: controls shared by both
   * views would otherwise let it start on the old one.
   */
  readyWhen?: string;
  /** Clicked when `readyWhen` is not on screen, e.g. the map/list toggle. */
  prepare?: string;
  /** Hidden from the menu when signed out. */
  requiresAuth?: boolean;
  /** Play once, automatically, on a first visit to a matching page. */
  autoStart?: boolean;
  /**
   * The welcome tour: plays by itself in a person's first login session (see
   * `/auth/me` first_login), taking the place of the page's own tour.
   */
  welcome?: boolean;
  /** Hidden from the menu when signed in (e.g. the visitor's home tour). */
  guestOnly?: boolean;
  steps: GuideStep[];
}


// Keep tours short: related controls share a step and its text lists them,
// rather than getting a step each. The welcome tour is the long one — it is
// the only tour a first-timer is sure to see, so it covers the whole app in
// one pass.

const WELCOME_TOUR: GuideTour = {
  id: 'welcome',
  title: 'Welcome — how it all works',
  path: '/',
  matches: (p) => p === '/',
  requiresAuth: true,
  welcome: true,
  steps: [
    {
      keep: true,
      title: 'Welcome 👋',
      description: `This network connects people who need something — a job, a skill, a service — with the people and organisations who offer it.
        This tour shows you how it all works in a minute. Use the arrow keys or the buttons; you can close it any time.`,
    },
    {
      element: ['[data-tour="profile-status"]', '[data-sidebar="sidebar"]'],
      keep: true,
      title: 'Your profile',
      description: `Your profile says who you are here and what you offer or look for. Its status decides who can see you:
        <ul>
          <li><b>Live</b>: others can find you, and you can connect.</li>
          <li><b>Draft</b>: not finished yet — complete the required fields to go live.</li>
          <li><b>Paused</b>: hidden until you resume it.</li>
        </ul>`,
    },
    {
      element: ['[data-tour="map"]', '[data-tour="view-map"]', '[data-tour="view-toggle"]'],
      keep: true,
      title: 'Map view',
      description: `See who is around you.
        <ul>
          <li><b>Pins and clusters</b>: a number is a group — zoom in or click it to spread it out.</li>
          <li><b>Search this area</b> after you move the map; the count shows how many are on it.</li>
          <li><b>Full screen</b> for a bigger map.</li>
        </ul>`,
    },
    {
      element: ['[data-tour="card-grid"]', '[data-tour="view-list"]', '[data-tour="view-toggle"]'],
      keep: true,
      title: 'List view',
      description: `The same people as cards, best matches first.
        <ul>
          <li>Each card shows the key details and a <b>match score</b>.</li>
          <li>Switch between map and list with the icons at the top right.</li>
          <li>Tick cards to connect with several at once.</li>
        </ul>`,
    },
    {
      element: ['[data-tour="search"]', '[data-testid="browse-toolbar"]'],
      title: 'Search and filters',
      description: `
        <ul>
          <li><b>Search</b> by name, skill or place.</li>
          <li>The bar below: choose <b>who</b> to see, <b>sort</b>, set a <b>distance</b> and add <b>filters</b>; applied filters show as chips.</li>
        </ul>`,
    },
    {
      element: ['[data-tour="card-action"]', '[data-tour="card-match-score"]', '[data-tour="card-grid"]'],
      keep: true,
      title: 'Connect or apply',
      description: `Found someone? Send a request from their card (<b>Connect</b> or <b>Apply</b>).
        <ul>
          <li><b>Match score</b>: how well they fit your profile.</li>
          <li>They are told, and can accept or reject.</li>
        </ul>`,
    },
    {
      keep: true,
      title: 'Your privacy',
      description: `Names and contact details stay hidden until a request is accepted — yours and theirs.
        Until then each side sees only what the other chose to show on their profile.`,
    },
    {
      element: ['[data-tour="notifications"]', '[data-sidebar="sidebar"]'],
      keep: true,
      title: 'Replies and requests',
      description: `The <b>bell</b> shows requests waiting for you. It opens <b>My Actions</b>, where everything you sent and received is in one list:
        accept or reject, follow a request's status, and export the ones that were accepted.`,
    },
    {
      element: '[data-tour="guide-button"]',
      keep: true,
      title: 'Help is always here',
      description: 'Open this menu any time for a closer look at the page you are on — the map, the list, your profile or My Actions.',
    },
  ],
};

const HOME_TOUR: GuideTour = {
  id: 'home',
  title: 'Get around the app',
  path: '/',
  matches: (p) => p === '/',
  autoStart: true,
  guestOnly: true,
  steps: [
    {
      element: '[data-tour="guest-hero"]',
      keep: true,
      title: 'Welcome 👋',
      description:
        'This short tour shows you how to find people and services on the network. Use the arrow keys or the buttons to move through it. Browsing as a visitor? You can look around freely; sign in to create a profile and connect.',
    },
    {
      element: '[data-sidebar="sidebar"]',
      title: 'Side panel',
      description: `
        <ul>
          <li><b>My Profile(s)</b>: create your profile, or manage the ones you have.</li>
          <li><b>My Actions</b>: requests you have sent and received.</li>
        </ul>`,
    },
    {
      element: ['[data-tour="search"]', '[data-testid="browse-toolbar"]'],
      title: 'Find what you need',
      description: `
        <ul>
          <li><b>Search</b>: type a name, skill or place.</li>
          <li><b>Map or list</b>: the two icons on the right switch views.</li>
          <li><b>The bar below</b>: choose a type, sort, set a location and add filters.</li>
        </ul>`,
    },
    {
      element: ['[data-tour="account"]', '[data-tour="preferences"]'],
      title: 'Language, theme and account',
      description: `
        <ul>
          <li><b>Language</b> and <b>light/dark mode</b> are next to your account.</li>
          <li><b>Log in</b> to create your profile and respond to requests; once signed in, the bell shows pending requests.</li>
        </ul>`,
    },
    {
      element: '[data-tour="guide-button"]',
      keep: true,
      title: 'Help is always here',
      description: 'Open this menu any time for a tour of the page you are on, or to learn how to do something else.',
    },
  ],
};

const CREATE_PROFILE_TOUR: GuideTour = {
  id: 'create-profile',
  title: 'Create your profile',
  path: '/profile/new',
  matches: (p) => p.startsWith('/profile/'),
  requiresAuth: true,
  steps: [
    {
      element: ['[data-tour="role-picker"]', '[data-tour="profile-hero"]'],
      keep: true,
      title: 'Choose your role',
      description:
        'Your profile is how others on the network find you. First pick the role that fits you; the form asks for details that matter for that role, and its header shows which one you chose.',
    },
    {
      element: '#profile-form',
      keep: true,
      title: 'Fill in your details',
      description: `
        <ul>
          <li>Work through each section. Fields marked <b>*</b> are required; the rest help others find you.</li>
          <li>Hold digital credentials in a wallet? <b>Import credentials</b> above the form fills parts of it for you.</li>
        </ul>`,
    },
    {
      element: '[data-testid="profile-action-bar"]',
      title: 'Check your progress',
      description: 'This bar tells you whether all required fields are complete, or what still needs fixing. When asked, tick the consent box to agree to how your details are used.',
    },
    {
      element: 'button[form="profile-form"]',
      title: 'Save',
      description: 'Becomes active once the form is complete and consent is ticked. Your profile then appears on the network. Use Cancel to leave without saving.',
    },
  ],
};

const MANAGE_PROFILE_TOUR: GuideTour = {
  id: 'manage-profile',
  title: 'Manage your profile',
  path: '/',
  // The side panel with your profiles is on every page.
  matches: () => true,
  requiresAuth: true,
  steps: [
    {
      element: ['[data-tour="profile-status"]', '[data-sidebar="sidebar"]'],
      keep: true,
      title: 'Your profiles and their status',
      description: `Your profiles are listed in the side panel, each with a status and some small icons.
        <ul>
          <li><b>Active</b>: live and discoverable by others.</li>
          <li><b>Paused</b>: hidden for now; resume any time.</li>
          <li><b>Draft</b>: required details are missing, so it is not visible yet.</li>
        </ul>`,
    },
    {
      element: ['[data-tour="profile-actions"] > button:first-child', '[data-tour="profile-actions"]'],
      title: 'Share',
      description:
        'Opens a QR code and a link to your public profile. Copy the link to send it, or download the QR to print or show on your phone. Only active profiles can be shared.',
    },
    {
      element: '[data-tour="profile-edit"]',
      title: 'Edit',
      description: 'Update your details any time. Changes show on the network once saved, and a draft goes live once it is complete.',
    },
    {
      element: ['[data-tour="profile-pause"]', '[data-tour="profile-resume"]'],
      title: 'Pause and resume',
      description: `
        <ul>
          <li><b>Pause</b>: hides your profile. No new requests can start and ones in progress wait. Existing connections stay, but your contact details are hidden. Nothing is deleted.</li>
          <li><b>Resume</b> (shown while paused): makes it discoverable again. If details are missing it stays a draft until you finish them.</li>
        </ul>`,
    },
    {
      element: '[data-tour="profile-retire"]',
      title: 'Retire',
      description:
        '<b>Permanent.</b> Removes the profile from the network and cancels any open requests on it. This cannot be undone. Use Pause instead if you might come back.',
    },
  ],
};

const MY_ACTIONS_TOUR: GuideTour = {
  id: 'my-actions',
  title: 'Manage your connections',
  path: '/my-actions',
  matches: (p) => p.startsWith('/my-actions'),
  // The rows (review strip, checkboxes) render after the list loads; wait for
  // them, or the later steps settle on the table's loading skeleton.
  readyWhen: '[data-tour="action-table"][data-loaded="true"]',
  requiresAuth: true,
  steps: [
    {
      element: ['[data-tour="action-views"]', '[data-tour="action-table"]'],
      keep: true,
      title: 'One list, sent and received',
      description: `Every request you send or receive is in this one list; the <b>Direction</b> column says which.
        <b>Views</b> jump to a ready-made list, each with its count:
        <ul>
          <li><b>Needs my response</b>: requests waiting for your reply.</li>
          <li><b>Ready to export</b>: accepted or completed ones.</li>
          <li><b>Sent by me</b>: requests you made.</li>
        </ul>`,
    },
    {
      element: ['[data-tour="action-filter"]', '[data-tour="action-search"]'],
      title: 'Search, filter and sort',
      description: `
        <ul>
          <li><b>Search</b> by name: only names you can already see match.</li>
          <li><b>Filter</b> by direction, status, action type and profile fields such as education or skills. Applied filters show as chips; remove one with ×.</li>
          <li><b>Sort</b> by updated, match score or distance, or click a column heading. <b>Columns</b> hides the ones you don't need.</li>
        </ul>`,
    },
    {
      element: '[data-tour="action-table"]',
      keep: true,
      title: 'Reading a request',
      description: `Each row is one request: who it is with, what it is for, its status and which of your profiles it belongs to.
        <ul>
          <li><b>Match score</b>: how well they fit your profile. “Not scored” means it has not been worked out.</li>
          <li><b>Distance</b>: how far away they are.</li>
          <li>Names and contact details show only once a request is accepted.</li>
        </ul>`,
    },
    {
      element: ['[data-tour="action-review"]', '[data-tour="action-table"]'],
      keep: true,
      title: 'Respond',
      description: `A request waiting for your reply shows <b>Needs your review</b> with a few details about them.
        <ul>
          <li><b>Accept</b> or <b>Reject</b> it, or <b>View profile</b> first.</li>
          <li>The <b>⋯</b> menu on each row has the rest: withdraw a request you sent, mark one complete, export a profile.</li>
        </ul>`,
    },
    {
      element: ['[data-tour="action-select"]', '[data-tour="action-table"]'],
      title: 'Act on many at once',
      description: `Tick rows (or <b>Select all</b>) to act on them together:
        <ul>
          <li><b>Accept</b> or <b>Reject</b> every waiting request you picked.</li>
          <li><b>Export seekers</b>, <b>Export service providers</b>…: one Excel file per type, for accepted or completed requests.</li>
        </ul>
        No checkboxes means there is nothing you can do in bulk yet.`,
    },
  ],
};

const MAP_TOUR: GuideTour = {
  id: 'map',
  title: 'Use the map',
  path: '/',
  matches: (p) => p === '/',
  readyWhen: '[data-tour="map-location"]',
  prepare: '[data-tour="view-map"]',
  steps: [
    {
      element: ['[data-testid="browse-toolbar"]', '[data-tour="domain-control"]'],
      keep: true,
      title: 'What to show and where',
      description: `
        <ul>
          <li><b>Types</b> (left): tap to show or hide. The map can show several at once; each has its own pin icon.</li>
          <li><b>Location</b>: centre on <b>My profile</b> or <b>This device</b> (your browser asks permission). The “You” marker sits there.</li>
        </ul>`,
    },
    {
      element: '[data-tour="map"]',
      keep: true,
      title: 'Zoom, pins and clusters',
      description: `
        <ul>
          <li><b>Move</b>: drag; zoom with + / −, scroll or pinch.</li>
          <li><b>A circle with a number</b> groups nearby listings; the icons under it count each type. Click to split it.</li>
          <li><b>A pin</b> is one listing. Click for <b>View details</b>, <b>See Match Score</b> and its request button, <b>Connect</b> or <b>Apply</b> depending on the listing.</li>
        </ul>`,
    },
    {
      element: ['[data-tour="map-count"]', '[data-testid="toolbar-count"]'],
      title: 'Counts',
      description: `
        <ul>
          <li><b>Bottom of the map</b>: listings in the area you are looking at; a zoom icon means too many to draw, so zoom in.</li>
          <li><b>Top right of the bar</b>: all matches anywhere. “Not on the map” have no location; find them in the list.</li>
        </ul>`,
    },
    {
      element: ['[data-testid="search-this-area"]', '[data-tour="map-maximize"]'],
      title: 'Search an area, full screen',
      description: `
        <ul>
          <li>Zoom in on a region and <b>Search this area</b> appears at the bottom; it lists only the listings there.</li>
          <li>This button makes the map full screen; filters and location stay in the corner.</li>
        </ul>`,
    },
    {
      element: '[data-tour="view-toggle"]',
      title: 'Prefer a list?',
      description: 'Switch to the list to sort, set a distance and compare cards side by side.',
    },
  ],
};

const LIST_TOUR: GuideTour = {
  id: 'list',
  title: 'Browse the list',
  path: '/',
  matches: (p) => p === '/',
  readyWhen: '[data-tour="browse-sort"]',
  prepare: '[data-tour="view-list"]',
  steps: [
    {
      element: ['[data-tour="browse-sort"]', '[data-testid="browse-toolbar"]'],
      keep: true,
      title: 'Type and sort',
      description: `The list shows one type at a time; pick it on the left. Then sort:
        <ul>
          <li><b>Relevance to your profile</b> or <b>to your search</b>: best fit first.</li>
          <li><b>Newest</b>: by when it was posted.</li>
          <li><b>Nearest</b>: closest first, from your Location choice.</li>
        </ul>`,
    },
    {
      element: ['[data-tour="browse-location"]', '[data-tour="browse-filters"]'],
      title: 'Distance and filters',
      description: `
        <ul>
          <li><b>Location</b>: anywhere, within a distance of your profile or device, a custom distance, or “this area” from the map.</li>
          <li><b>Filters</b>: details such as skills, experience or category. Chips show what is applied; Clear all resets.</li>
        </ul>`,
    },
    {
      element: ['[data-tour="bulk-select"]', '[data-testid="toolbar-count"]'],
      title: 'Results and selecting',
      description: 'The count shows how many listings match. <b>Select</b> lets you pick several cards and act on them together, for example to send the same request to each.',
    },
    {
      element: '[data-tour="card-grid"]',
      keep: true,
      title: 'Cards and match score',
      description: `
        <ul>
          <li>Each card is one listing with its key details; <b>View more details</b> shows everything shared publicly.</li>
          <li><b>See Match Score</b>: how well it fits your profile, 0–100%, with a breakdown (shown when you have a matching profile).</li>
        </ul>`,
    },
    {
      element: ['[data-tour="card-actions"]', '[data-tour="card-action"]'],
      title: 'Take action',
      description: 'Buttons here start a request, such as Connect or Apply. The options depend on the listing and your profile.',
    },
  ],
};

const CONNECT_TOUR: GuideTour = {
  id: 'connect',
  title: 'Connect or apply',
  path: '/',
  matches: (p) => p === '/',
  readyWhen: '[data-tour="browse-sort"]',
  prepare: '[data-tour="view-list"]',
  requiresAuth: true,
  steps: [
    {
      title: 'Connect or apply',
      description: 'Find a person or listing, check how well they fit, then send a request: <b>Connect</b> for people and services, <b>Apply</b> for jobs and openings; the button on each card shows which. Contact details are shared only after they accept. You need an active profile to send requests.',
    },
    {
      element: '[data-tour="search"]',
      title: '1. Find someone',
      description: 'Search, sort and filter the list, or click a pin on the map, to find a listing that interests you.',
    },
    {
      element: ['[data-tour="card-match-score"]', '[data-tour="card-grid"]'],
      keep: true,
      title: '2. Check the fit',
      description: 'On a card, <b>See Match Score</b> compares their profile with yours. The <b>Proceed</b> button in the details sends the same request as the card’s own button (Connect or Apply), so you can go straight on.',
    },
    {
      element: ['[data-tour="card-action"]', '[data-tour="card-grid"]'],
      keep: true,
      title: '3. Send a request',
      description: 'Click the card’s request button: <b>Connect</b> or <b>Apply</b>, depending on the listing. You may be asked for a few details or a note, then confirm.',
    },
    {
      element: '[data-sidebar="sidebar"]',
      keep: true,
      title: '4. Follow up',
      description: 'Your request appears in <b>My Actions</b> under Initiated. You will see when it is accepted, and their contact details then become visible.',
    },
  ],
};

export const TOURS: GuideTour[] = [
  WELCOME_TOUR,
  HOME_TOUR,
  MAP_TOUR,
  LIST_TOUR,
  CONNECT_TOUR,
  CREATE_PROFILE_TOUR,
  MANAGE_PROFILE_TOUR,
  MY_ACTIONS_TOUR,
];

export function findTour(id: string): GuideTour | undefined {
  return TOURS.find((t) => t.id === id);
}
