/**
 * Guided-tour definitions. SPIKE — not production content.
 *
 * A tour is plain data: an ordered list of steps, each pointing at a
 * `[data-tour="…"]` anchor (or no anchor, for a centred intro/outro card).
 * Keeping tours as data — not code — is the point: the same shape can later be
 * hand-written, generated by an AI from the app's knowledge base, or served by
 * an API, and the player in `run-tour.ts` stays unchanged.
 *
 * Steps whose anchor is not on screen are skipped (or, with `keep`, shown as a
 * centred card), so one tour can span page states — e.g. the profile role
 * picker and the form that follows it.
 */
export interface GuideStep {
  /**
   * Element to highlight. A list is tried in order and the first one on screen
   * wins. Omit for a centred card.
   */
  element?: string | string[];
  /**
   * Show the step as a centred card when none of its elements are on screen,
   * instead of skipping it. For steps whose text matters on its own.
   */
  keep?: boolean;
  title: string;
  description: string;
}

export interface GuideTour {
  id: string;
  /** Shown in the "How do I…" menu. */
  title: string;
  /**
   * Where the tour starts. The menu goes here first when `matches` is false;
   * on the same page only its query is merged in, so the chosen network stays.
   * (Views such as map/list are switched with `prepare`, not the URL: the home
   * page reads `?view=` only on load.)
   */
  path: string;
  /** Whether this tour belongs to the current page (and view). */
  matches: (pathname: string, params: URLSearchParams) => boolean;
  /**
   * An element that proves the page (or view) the tour is about is on screen.
   * Needed when starting the tour switches views: controls shared by both
   * views would otherwise let it start on the old one.
   */
  readyWhen?: string;
  /** Clicked when `readyWhen` is not on screen, e.g. the map/list toggle. */
  prepare?: string;
  /** Hidden from the menu when signed out. */
  requiresAuth?: boolean;
  /** Play once, automatically, on a first visit to a matching page. */
  autoStart?: boolean;
  steps: GuideStep[];
}


// Every tour is capped at five steps: related controls share a step and its
// text lists them, rather than getting a step each.

const HOME_TOUR: GuideTour = {
  id: 'home',
  title: 'Get around the app',
  path: '/',
  matches: (p) => p === '/',
  autoStart: true,
  steps: [
    {
      element: '[data-tour="guest-hero"]',
      keep: true,
      title: 'Welcome 👋',
      description:
        'This short tour shows you how to find people and services on the network. Use the arrow keys or the buttons to move through it. Browsing as a visitor? You can look around freely; sign in to create a profile and connect.',
    },
    {
      element: '[data-sidebar="sidebar"]',
      title: 'Side panel',
      description: `
        <ul>
          <li><b>My Profile(s)</b>: create your profile, or manage the ones you have.</li>
          <li><b>My Actions</b>: requests you have sent and received.</li>
        </ul>`,
    },
    {
      element: ['[data-tour="search"]', '[data-testid="browse-toolbar"]'],
      title: 'Find what you need',
      description: `
        <ul>
          <li><b>Search</b>: type a name, skill or place.</li>
          <li><b>Map or list</b>: the two icons on the right switch views.</li>
          <li><b>The bar below</b>: choose a type, sort, set a location and add filters.</li>
        </ul>`,
    },
    {
      element: ['[data-tour="account"]', '[data-tour="preferences"]'],
      title: 'Language, theme and account',
      description: `
        <ul>
          <li><b>Language</b> and <b>light/dark mode</b> are next to your account.</li>
          <li><b>Log in</b> to create your profile and respond to requests; once signed in, the bell shows pending requests.</li>
        </ul>`,
    },
    {
      element: '[data-tour="guide-button"]',
      keep: true,
      title: 'Help is always here',
      description: 'Open this menu any time for a tour of the page you are on, or to learn how to do something else.',
    },
  ],
};

const CREATE_PROFILE_TOUR: GuideTour = {
  id: 'create-profile',
  title: 'Create your profile',
  path: '/profile/new',
  matches: (p) => p.startsWith('/profile/'),
  requiresAuth: true,
  steps: [
    {
      element: ['[data-tour="role-picker"]', '[data-tour="profile-hero"]'],
      keep: true,
      title: 'Choose your role',
      description:
        'Your profile is how others on the network find you. First pick the role that fits you; the form asks for details that matter for that role, and its header shows which one you chose.',
    },
    {
      element: '#profile-form',
      keep: true,
      title: 'Fill in your details',
      description: `
        <ul>
          <li>Work through each section. Fields marked <b>*</b> are required; the rest help others find you.</li>
          <li>Hold digital credentials in a wallet? <b>Import credentials</b> above the form fills parts of it for you.</li>
        </ul>`,
    },
    {
      element: '[data-testid="profile-action-bar"]',
      title: 'Check your progress',
      description: 'This bar tells you whether all required fields are complete, or what still needs fixing. When asked, tick the consent box to agree to how your details are used.',
    },
    {
      element: 'button[form="profile-form"]',
      title: 'Save',
      description: 'Becomes active once the form is complete and consent is ticked. Your profile then appears on the network. Use Cancel to leave without saving.',
    },
  ],
};

const MANAGE_PROFILE_TOUR: GuideTour = {
  id: 'manage-profile',
  title: 'Manage your profile',
  path: '/',
  // The side panel with your profiles is on every page.
  matches: () => true,
  requiresAuth: true,
  steps: [
    {
      element: ['[data-tour="profile-status"]', '[data-sidebar="sidebar"]'],
      keep: true,
      title: 'Your profiles and their status',
      description: `Your profiles are listed in the side panel, each with a status and some small icons.
        <ul>
          <li><b>Active</b>: live and discoverable by others.</li>
          <li><b>Paused</b>: hidden for now; resume any time.</li>
          <li><b>Draft</b>: required details are missing, so it is not visible yet.</li>
        </ul>`,
    },
    {
      element: ['[data-tour="profile-actions"] > button:first-child', '[data-tour="profile-actions"]'],
      title: 'Share',
      description:
        'Opens a QR code and a link to your public profile. Copy the link to send it, or download the QR to print or show on your phone. Only active profiles can be shared.',
    },
    {
      element: '[data-tour="profile-edit"]',
      title: 'Edit',
      description: 'Update your details any time. Changes show on the network once saved, and a draft goes live once it is complete.',
    },
    {
      element: ['[data-tour="profile-pause"]', '[data-tour="profile-resume"]'],
      title: 'Pause and resume',
      description: `
        <ul>
          <li><b>Pause</b>: hides your profile. No new requests can start and ones in progress wait. Existing connections stay, but your contact details are hidden. Nothing is deleted.</li>
          <li><b>Resume</b> (shown while paused): makes it discoverable again. If details are missing it stays a draft until you finish them.</li>
        </ul>`,
    },
    {
      element: '[data-tour="profile-retire"]',
      title: 'Retire',
      description:
        '<b>Permanent.</b> Removes the profile from the network and cancels any open requests on it. This cannot be undone. Use Pause instead if you might come back.',
    },
  ],
};

const MY_ACTIONS_TOUR: GuideTour = {
  id: 'my-actions',
  title: 'Manage your requests',
  path: '/my-actions',
  matches: (p) => p.startsWith('/my-actions'),
  requiresAuth: true,
  steps: [
    {
      element: '[data-tour="action-tabs"]',
      keep: true,
      title: 'Initiated and received',
      description: `Every request you send or receive lives here.
        <ul>
          <li><b>Initiated</b>: requests you made to others.</li>
          <li><b>Received</b>: requests others made to you.</li>
        </ul>
        The number on each tab shows how many there are.`,
    },
    {
      element: '[data-testid="sort-trigger"]',
      title: 'Sort',
      description: `
        <ul>
          <li><b>Match score</b>: best fit with your profile first.</li>
          <li><b>Newest</b>: most recent first (the default).</li>
          <li><b>Oldest</b>: longest-waiting first, handy for clearing a backlog.</li>
          <li><b>Distance</b>: closest to you first.</li>
        </ul>`,
    },
    {
      element: '[data-testid="filters-button"]',
      title: 'Filter and refresh',
      description: `
        <ul>
          <li><b>Status</b>: Pending (waiting for a reply), Accepted (includes completed), Rejected (includes cancelled).</li>
          <li><b>Action type</b> and <b>profile fields</b> such as skills or location.</li>
          <li>Applied filters show as chips; remove with × or Clear. <b>Refresh</b> on the right fetches the latest status.</li>
        </ul>`,
    },
    {
      element: ['[data-tour="action-list"]', '[data-tour="action-tabs"]'],
      keep: true,
      title: 'Reading a request',
      description: `Each card is one request: who it is with, what it is for, and its status.
        <ul>
          <li><b>Match score</b>: how well they fit your profile, 0–100%, worked out when the request was made. “Not scored yet” means it is still being calculated.</li>
          <li><b>Distance</b>: how far away they are.</li>
          <li>Contact details are revealed only after a request is accepted.</li>
        </ul>`,
    },
    {
      element: '[data-tour="action-respond"]',
      keep: true,
      title: 'Respond',
      description: `
        <ul>
          <li><b>View profile</b>: see the other person’s details.</li>
          <li><b>Received</b>: Accept or Decline; once accepted, mark it Complete.</li>
          <li><b>Initiated</b>: Cancel if you no longer need it.</li>
        </ul>`,
    },
  ],
};

const MAP_TOUR: GuideTour = {
  id: 'map',
  title: 'Use the map',
  path: '/',
  matches: (p) => p === '/',
  readyWhen: '[data-tour="map-location"]',
  prepare: '[data-tour="view-map"]',
  steps: [
    {
      element: ['[data-testid="browse-toolbar"]', '[data-tour="domain-control"]'],
      keep: true,
      title: 'What to show and where',
      description: `
        <ul>
          <li><b>Types</b> (left): tap to show or hide. The map can show several at once; each has its own pin icon.</li>
          <li><b>Location</b>: centre on <b>My profile</b> or <b>This device</b> (your browser asks permission). The “You” marker sits there.</li>
        </ul>`,
    },
    {
      element: '[data-tour="map"]',
      keep: true,
      title: 'Zoom, pins and clusters',
      description: `
        <ul>
          <li><b>Move</b>: drag; zoom with + / −, scroll or pinch.</li>
          <li><b>A circle with a number</b> groups nearby listings; the icons under it count each type. Click to split it.</li>
          <li><b>A pin</b> is one listing. Click for <b>View details</b>, <b>See Match Score</b> and its request button, <b>Connect</b> or <b>Apply</b> depending on the listing.</li>
        </ul>`,
    },
    {
      element: ['[data-tour="map-count"]', '[data-testid="toolbar-count"]'],
      title: 'Counts',
      description: `
        <ul>
          <li><b>Bottom of the map</b>: listings in the area you are looking at; a zoom icon means too many to draw, so zoom in.</li>
          <li><b>Top right of the bar</b>: all matches anywhere. “Not on the map” have no location; find them in the list.</li>
        </ul>`,
    },
    {
      element: ['[data-testid="search-this-area"]', '[data-tour="map-maximize"]'],
      title: 'Search an area, full screen',
      description: `
        <ul>
          <li>Zoom in on a region and <b>Search this area</b> appears at the bottom; it lists only the listings there.</li>
          <li>This button makes the map full screen; filters and location stay in the corner.</li>
        </ul>`,
    },
    {
      element: '[data-tour="view-toggle"]',
      title: 'Prefer a list?',
      description: 'Switch to the list to sort, set a distance and compare cards side by side.',
    },
  ],
};

const LIST_TOUR: GuideTour = {
  id: 'list',
  title: 'Browse the list',
  path: '/',
  matches: (p) => p === '/',
  readyWhen: '[data-tour="browse-sort"]',
  prepare: '[data-tour="view-list"]',
  steps: [
    {
      element: ['[data-tour="browse-sort"]', '[data-testid="browse-toolbar"]'],
      keep: true,
      title: 'Type and sort',
      description: `The list shows one type at a time; pick it on the left. Then sort:
        <ul>
          <li><b>Relevance to your profile</b> or <b>to your search</b>: best fit first.</li>
          <li><b>Newest</b>: by when it was posted.</li>
          <li><b>Nearest</b>: closest first, from your Location choice.</li>
        </ul>`,
    },
    {
      element: ['[data-tour="browse-location"]', '[data-tour="browse-filters"]'],
      title: 'Distance and filters',
      description: `
        <ul>
          <li><b>Location</b>: anywhere, within a distance of your profile or device, a custom distance, or “this area” from the map.</li>
          <li><b>Filters</b>: details such as skills, experience or category. Chips show what is applied; Clear all resets.</li>
        </ul>`,
    },
    {
      element: ['[data-tour="bulk-select"]', '[data-testid="toolbar-count"]'],
      title: 'Results and selecting',
      description: 'The count shows how many listings match. <b>Select</b> lets you pick several cards and act on them together, for example to send the same request to each.',
    },
    {
      element: '[data-tour="card-grid"]',
      keep: true,
      title: 'Cards and match score',
      description: `
        <ul>
          <li>Each card is one listing with its key details; <b>View more details</b> shows everything shared publicly.</li>
          <li><b>See Match Score</b>: how well it fits your profile, 0–100%, with a breakdown (shown when you have a matching profile).</li>
        </ul>`,
    },
    {
      element: ['[data-tour="card-actions"]', '[data-tour="card-action"]'],
      title: 'Take action',
      description: 'Buttons here start a request, such as Connect or Apply. The options depend on the listing and your profile.',
    },
  ],
};

const CONNECT_TOUR: GuideTour = {
  id: 'connect',
  title: 'Connect or apply',
  path: '/',
  matches: (p) => p === '/',
  readyWhen: '[data-tour="browse-sort"]',
  prepare: '[data-tour="view-list"]',
  requiresAuth: true,
  steps: [
    {
      title: 'Connect or apply',
      description: 'Find a person or listing, check how well they fit, then send a request: <b>Connect</b> for people and services, <b>Apply</b> for jobs and openings; the button on each card shows which. Contact details are shared only after they accept. You need an active profile to send requests.',
    },
    {
      element: '[data-tour="search"]',
      title: '1. Find someone',
      description: 'Search, sort and filter the list, or click a pin on the map, to find a listing that interests you.',
    },
    {
      element: ['[data-tour="card-match-score"]', '[data-tour="card-grid"]'],
      keep: true,
      title: '2. Check the fit',
      description: 'On a card, <b>See Match Score</b> compares their profile with yours. The <b>Proceed</b> button in the details sends the same request as the card’s own button (Connect or Apply), so you can go straight on.',
    },
    {
      element: ['[data-tour="card-action"]', '[data-tour="card-grid"]'],
      keep: true,
      title: '3. Send a request',
      description: 'Click the card’s request button: <b>Connect</b> or <b>Apply</b>, depending on the listing. You may be asked for a few details or a note, then confirm.',
    },
    {
      element: '[data-sidebar="sidebar"]',
      keep: true,
      title: '4. Follow up',
      description: 'Your request appears in <b>My Actions</b> under Initiated. You will see when it is accepted, and their contact details then become visible.',
    },
  ],
};

export const TOURS: GuideTour[] = [
  HOME_TOUR,
  MAP_TOUR,
  LIST_TOUR,
  CONNECT_TOUR,
  CREATE_PROFILE_TOUR,
  MANAGE_PROFILE_TOUR,
  MY_ACTIONS_TOUR,
];

export function findTour(id: string): GuideTour | undefined {
  return TOURS.find((t) => t.id === id);
}
