/**
 * Client and assertions for the notification sink.
 *
 * Resolving a captured mail back to its case is the whole problem here: every
 * email leaves as template_id `basic_email` (dispatch_email.ts:149), so the
 * wire cannot say which of the 35 cases it was. We instead read the same
 * messages.properties the API loads, turn the case's subject template into a
 * regex, and match on (recipient, subject) — which also means a copy edit that
 * skips this manifest breaks loudly rather than silently passing.
 *
 * NOTE ON THE CASE COUNT: at the time this suite was written the count was
 * believed to be 35 (19 static `CASES.set` calls + 16 generated by the
 * `action.<group>.<role>.<shape>` loop in email_cases.ts). Direct inspection
 * during this task found the registry currently holds 39 (23 static + the
 * same 16 generated — `profile.pause`/`offer.pause`/`profile.retire`/
 * `offer.retire` postdate the earlier count), and all 39 have matching copy
 * in messages.default.properties with zero orphans today. Rather than bake
 * either number in, `emailCaseIds()`/`emailCaseInventory()` below read the
 * registry live, so this file is correct regardless of which count is
 * current — see the task-5 report for the discrepancy.
 */

import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export interface Captured {
  channel: string;
  to: string;
  subject?: string;
  html?: string;
  templateId: string;
  variables: Record<string, unknown>;
}

const TOKEN = /\{\{\s*[\w.]+\s*\}\}/g;

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

export function subjectPatternFor(caseId: string, properties: string): RegExp {
  const line = properties
    .split('\n')
    .find((l) => l.startsWith(`${caseId}.subject=`));
  if (!line) {
    throw new Error(
      `[e2e] no subject copy for email case "${caseId}" in the messages file. ` +
        'Either the case id is wrong or the copy moved — check ' +
        'apps/api/src/notifications/email/messages.default.properties.',
    );
  }
  const template = line.slice(`${caseId}.subject=`.length).trim();
  const pattern = template
    .split(TOKEN)
    .map(escapeRe)
    .join('.+?');
  return new RegExp(`^${pattern}$`);
}

/**
 * Three invariants over every message a run captured. Applied to the whole set
 * rather than per assertion, so one sweep covers all the cases and catches copy
 * drift in a case no individual test named.
 */
export function assertNoCopyDrift(all: Captured[]): void {
  for (const m of all) {
    const body = `${m.subject ?? ''}\n${m.html ?? ''}`;
    const token = body.match(TOKEN);
    if (token) {
      throw new Error(`[e2e] unsubstituted token ${token[0]} in a "${m.subject}" message to ${m.to}`);
    }
    if (body.includes('__SUPPORT_EMAIL__')) {
      throw new Error(`[e2e] unresolved __SUPPORT_EMAIL__ in a "${m.subject}" message to ${m.to}`);
    }
    for (const href of [...body.matchAll(/href="([^"]*)"/g)].map((x) => x[1])) {
      // Empty string is NOT skipped here (fix round 1, finding 3): the plain
      // shell never emits `href=""`, but the CTA shell's `ctaUrl ?? ''`
      // fallback can, and a button that links nowhere is exactly the broken
      // mail this invariant exists to catch — the original `if (href && ...)`
      // guard let it through by treating '' as "nothing to check".
      if (href === '') {
        throw new Error(`[e2e] empty CTA href in a "${m.subject}" message to ${m.to} — the button links nowhere`);
      }
      if (!/^https?:\/\//.test(href) && !href.startsWith('mailto:')) {
        throw new Error(`[e2e] relative CTA href "${href}" in a "${m.subject}" message — mail clients cannot resolve it`);
      }
    }
  }
}

/**
 * Stricter, OPT-IN CTA check layered on top of the always-on floor above.
 * `assertNoCopyDrift` only proves a CTA href is SOME absolute URL — it
 * happily passes a link to the wrong product on the same host. A live send
 * during fix round 1 of this task confirmed this happens in practice:
 * login.otp's CTA came back as http://localhost:3000, which on that machine
 * is the aggregator portal, not Signals (:5173) — an absolute, well-formed,
 * entirely wrong link. Call this ADDITIONALLY whenever the caller actually
 * knows what origin the CTA should open (e.g. the target config's own
 * uiBaseUrl); never hardcode a port here, since it varies per deployment.
 */
export function assertCtaOrigin(all: Captured[], expectedOrigin: string): void {
  for (const m of all) {
    const html = m.html ?? '';
    for (const href of [...html.matchAll(/href="(https?:\/\/[^"]*)"/g)].map((x) => x[1])) {
      let origin: string;
      try {
        origin = new URL(href).origin;
      } catch {
        continue; // not a parseable absolute URL — assertNoCopyDrift's job, not this one
      }
      if (origin !== expectedOrigin) {
        throw new Error(
          `[e2e] CTA href "${href}" in a "${m.subject}" message to ${m.to} opens ${origin}, not the expected ${expectedOrigin} — this link may point at the wrong product`,
        );
      }
    }
  }
}

export class NotifySink {
  // Not a TS parameter property (`constructor(private readonly baseUrl...)`):
  // node's `--experimental-strip-types` is strip-ONLY (no transform), and a
  // parameter property desugars into a field declaration as well as a
  // parameter, which isn't syntax it can strip — this is loaded directly by
  // `node --test` via notify.test.ts, not bundled by tsc/tsx first, so it has
  // to be plain-JS-with-type-annotations underneath the TS.
  private readonly baseUrl: string;

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl;
  }

  /**
   * Wraps `fetch` so a dead sink fails with an actionable message (fix round
   * 1, finding 4): a bare "fetch failed" names neither the URL nor the likely
   * cause, and forgetting to start notify-sink.mjs before a run is exactly
   * the mistake this exists to catch quickly.
   */
  private async request(path: string, init?: RequestInit): Promise<Response> {
    const url = `${this.baseUrl}${path}`;
    try {
      return await fetch(url, init);
    } catch (err) {
      throw new Error(
        `[e2e] could not reach the notification sink at ${url} — is notify-sink.mjs running? ` +
          `(${err instanceof Error ? err.message : String(err)})`,
      );
    }
  }

  async messages(q: Partial<Pick<Captured, 'to' | 'channel'>> = {}): Promise<Captured[]> {
    const params = new URLSearchParams();
    if (q.to) params.set('to', q.to);
    if (q.channel) params.set('channel', q.channel);
    const res = await this.request(`/_e2e/mail?${params}`);
    if (!res.ok) throw new Error(`[e2e] notify sink query failed: ${res.status}`);
    return (await res.json()) as Captured[];
  }

  async reset(): Promise<void> {
    await this.request('/_e2e/reset', { method: 'POST' });
  }

  async failNext(): Promise<void> {
    await this.request('/_e2e/fail-next', { method: 'POST' });
  }
}

// ── Case inventory ──────────────────────────────────────────────────────────
//
// Deliberately does NOT grep `CASES.set(` in email_cases.ts: 16 of the
// registered ids are produced by a nested loop over ACTION_GROUPS ×
// ACTION_ROLES × ACTION_SHAPES and never appear there as a literal string —
// a text scrape would silently miss all 16. Instead this executes the actual
// registry module (a dynamic import of its real source file) and reads back
// EMAIL_CASE_IDS, so the list can never drift from what the API itself sends,
// and reads the SMS side's raw `.properties` keys the same way messages.ts
// does (parseProperties, not a bespoke parser), so an added SMS case is
// picked up automatically too.

/**
 * Root of the Signals checkout this module introspects for the case registry
 * and the bundled copy files. Defaults to this worktree (e2e/ sits one level
 * below the repo root), but can be pointed at a different checkout with
 * SIGNALS_REPO — the SAME variable stack-up.sh already reads
 * (`SIGNALS_REPO=/path/to/main/checkout bash lib/stack-up.sh ...`), not a
 * second, differently-named one nobody would think to set. That script's own
 * comment explains why the two checkouts can differ: this is an e2e-only
 * worktree, and the stack actually running may be a sibling checkout
 * (typically the main Signals-DPG clone) whose working tree has diverged from
 * this one. Pointing here at that checkout keeps the oracle honest about what
 * the LIVE instance actually loaded. `E2E_SIGNALS_REPO` is accepted too, for
 * anyone who reached for this file's own `E2E_*` override convention first —
 * SIGNALS_REPO wins when both are set, since it's the name the documented
 * workflow actually uses.
 */
export function repoRoot(): string {
  const override = process.env.SIGNALS_REPO ?? process.env.E2E_SIGNALS_REPO;
  if (override) return override;
  const here = dirname(fileURLToPath(import.meta.url)); // e2e/src
  return resolve(here, '..', '..');
}

function emailCasesModulePath(): string {
  return resolve(repoRoot(), 'apps/api/src/notifications/email/email_cases.ts');
}

function parsePropertiesModulePath(): string {
  return resolve(repoRoot(), 'apps/api/src/notifications/email/parse_properties.ts');
}

export function defaultEmailPropertiesPath(): string {
  return resolve(repoRoot(), 'apps/api/src/notifications/email/messages.default.properties');
}

export function defaultSmsPropertiesPath(): string {
  return resolve(repoRoot(), 'apps/api/src/notifications/sms/sms.default.properties');
}

export function defaultEmailPropertiesText(): string {
  return readFileSync(defaultEmailPropertiesPath(), 'utf8');
}

export function defaultSmsPropertiesText(): string {
  return readFileSync(defaultSmsPropertiesPath(), 'utf8');
}

/**
 * The layered copy text for a network, in the order `subjectPatternFor`
 * needs: the network's `messages.properties` override BEFORE the bundled
 * defaults, because `subjectPatternFor`'s `.find()` returns the FIRST
 * "<id>.subject=" line it sees.
 *
 * This is PARTIAL fidelity to messages.ts's real precedence, not the full
 * chain — real precedence (docs/operations/email-copy-overrides.md) is
 * `defaults < instance override (EMAIL_MESSAGES_PATH) < network < brand`.
 * Two layers are deliberately not reproduced here, for different reasons:
 * the brand layer, because no send resolves a brand yet, so there is nothing
 * a live send could disagree with; and the instance-override layer
 * (EMAIL_MESSAGES_PATH), because it's silently skipped rather than
 * unreachable — harmless for a stock local run (that var isn't normally set
 * against this worktree's target), but a run against an instance that DOES
 * set EMAIL_MESSAGES_PATH would see this function's output disagree with
 * what that instance actually sends.
 */
export function layeredEmailPropertiesText(network: string | null): string {
  const defaults = defaultEmailPropertiesText();
  if (!network) return defaults;
  const overridePath = resolve(repoRoot(), 'examples/schemas', network, 'messages.properties');
  if (!existsSync(overridePath)) return defaults;
  return `${readFileSync(overridePath, 'utf8')}\n${defaults}`;
}

/**
 * Every registered email case id, read straight from the live registry
 * module rather than reproduced or grepped — see the block comment above.
 */
export async function emailCaseIds(): Promise<string[]> {
  const mod = (await import(emailCasesModulePath())) as { EMAIL_CASE_IDS: string[] };
  return mod.EMAIL_CASE_IDS;
}

export interface EmailCaseInventory {
  /** Every case id the registry will actually send. */
  registered: string[];
  /**
   * Case ids with subject copy in messages.default.properties but no matching
   * registry entry — dead copy that can never be sent (a doc/content update
   * that landed before, or instead of, the code that would fire it). Reported
   * rather than thrown: failing here would block on drift the sink didn't
   * cause and can't fix.
   */
  orphanedCopyIds: string[];
}

export async function emailCaseInventory(): Promise<EmailCaseInventory> {
  const registered = await emailCaseIds();
  const registeredSet = new Set(registered);
  const propsIds = new Set<string>();
  for (const line of defaultEmailPropertiesText().split('\n')) {
    const m = /^([\w.]+)\.subject=/.exec(line.trim());
    if (m) propsIds.add(m[1]);
  }
  return {
    registered,
    orphanedCopyIds: [...propsIds].filter((id) => !registeredSet.has(id)),
  };
}

/**
 * The 5 SMS case ids, read from the raw `.template_id` keys in
 * sms.default.properties (via the API's own tiny properties parser) rather
 * than hardcoded — a case whose `template_id` is blank is a DLT no-op, not a
 * failure (see dispatch_sms.ts): the correct assertion for those is that
 * nothing was posted at all, which is why this only returns ids, not
 * whether they're "active".
 */
export async function smsCaseIds(): Promise<string[]> {
  const mod = (await import(parsePropertiesModulePath())) as {
    parseProperties: (text: string) => { entries: Map<string, string> };
  };
  const parsed = mod.parseProperties(defaultSmsPropertiesText());
  const ids = new Set<string>();
  for (const key of parsed.entries.keys()) {
    if (key.endsWith('.template_id')) ids.add(key.slice(0, -'.template_id'.length));
  }
  return [...ids];
}
